### Create food
POST localhost:8080/api/v1/food/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA
Content-Type: application/json

{
  "price": 100000
}


### Update food
PUT localhost:8080/api/v1/food/update?id=2bd57a9c-9ed3-45a5-ab8c-3a5cfa202db7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA
Content-Type: application/json

{
  "name": "Alivye",
  "price": 99900
}

### Delete food
DELETE localhost:8080/api/v1/food/delete?id=2bd57a9c-9ed3-45a5-ab8c-3a5cfa202db7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA

###Get food by id
GET localhost:8080/api/v1/food/open/2bd57a9c-9ed3-45a5-ab8c-3a5cfa202db7


###paging food by category id
GET localhost:8080/api/v1/food/open/all




