### Create table
POST localhost:8080/api/v1/table
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA
Content-Type: application/json

{
  "type": 2,
  "number": 4
}

### Update table
PUT localhost:8080/api/v1/table?id=cfce5cb9-3d37-4c7f-a318-c61cadb843a9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA
Content-Type: application/json

{
  "type": 2,
  "number": 10
}

### Change status table
PUT localhost:8080/api/v1/table/change?id=3a2089f7-0a2c-4c5d-b466-6d23bd689eb8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA
Content-Type: application/json

{
  "isBusy": true
}


### Delete table
DELETE localhost:8080/api/v1/table?id=3a2089f7-0a2c-4c5d-b466-6d23bd689eb8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU0OTY3ODYsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzNjA3ODYsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.aWV4500yw-VjUIApg578uDm6-m7NAbqjuwKQdMXod_yzThHIsxEuB3oxAN8YnA8cw4_70j0Hb_87VoFF14VoDA

###Get table by id
GET localhost:8080/api/v1/table/open/get?id=3a2089f7-0a2c-4c5d-b466-6d23bd689eb8

###Get all table
GET localhost:8080/api/v1/table/open/get-all

###paging table
GET localhost:8080/api/v1/table/open/get-all-by


### bron table
PUT localhost:8080/api/v1/table/bron
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU1MTg4NDEsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiU1RBRkYiLCJDSEVGIiwiQURNSU5JU1RSQVRPUiJdLCJleHAiOjE3MDYzODI4NDEsImlzcyI6InJlc3RhdXJhbnQgUE9SVEFMIn0.-CBguPTC1RgzS-4lLhTnbTWNbjnYwZvcsHtxDfbOd6Saj3y61FTf0eKp0ON5gCjyEL7ERl7nu_yfV9iSrj5fbA
Content-Type: application/json

{
  "tableNumber": 2,
  "bronDate": "2024-01-18T10:00"
}

